apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-pod-monitor
  namespace: spark-jobs
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      name: spark-observability-demo

  podMetricsEndpoints:
    - port: jmx-exporter

  # propagate k8s pod labels to prometheus
  podTargetLabels:
    - spark-app-name
    - spark-role
