apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-observability-demo
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: apache/spark:4.2.0
  imagePullPolicy: IfNotPresent
  sparkVersion: "4.2.0"
  mainApplicationFile: "s3a://spark-workflows-demo/observability.py"

  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true

    prometheus:
      jmxExporterJar: "/jmx/jmx_prometheus_javaagent.jar"
      port: 8090
      configuration: |
        rules:
          - pattern: "."

  sparkConf:
    spark.jars.ivy: "/tmp/.ivy2"
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.5.0"
    spark.hadoop.fs.s3a.fast.upload: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"

    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-event-logs-demo/"
    spark.kubernetes.driver.log.dfsDir: "s3a://spark-event-logs-demo/logs"
    spark.kubernetes.executor.log.dfsDir: "s3a://spark-event-logs-demo/logs"

    spark.ui.acls.enable: "true"
    spark.ui.prometheus.enabled: "true"

  restartPolicy:
    type: Never

  volumes:
    - name: spark-code
      emptyDir: {}
    - name: jmx-exporter
      emptyDir: {}

  driver:
    initContainers:
      - name: download-jmx-exporter
        image: curlimages/curl:8.15.0
        command:
          - sh
          - -c
          - |
            curl -fL \
              -o /jmx/jmx_prometheus_javaagent.jar \
              https://github.com/prometheus/jmx_exporter/releases/download/1.1.0/jmx_prometheus_javaagent-1.1.0.jar
        volumeMounts:
          - name: jmx-exporter
            mountPath: /jmx

    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: spark-code
        mountPath: /opt/spark/jobs
      - name: jmx-exporter
        mountPath: /jmx
    labels:
      name: spark-observability-demo
      version: 4.2.0
    serviceAccount: spark-pod

  executor:
    initContainers:
      - name: download-jmx-exporter
        image: curlimages/curl:8.15.0
        command:
          - sh
          - -c
          - |
            curl -fL \
              -o /jmx/jmx_prometheus_javaagent.jar \
              https://github.com/prometheus/jmx_exporter/releases/download/1.1.0/jmx_prometheus_javaagent-1.1.0.jar
        volumeMounts:
          - name: jmx-exporter
            mountPath: /jmx

    cores: 1
    instances: 2
    memory: "512m"
    serviceAccount: spark-pod
    labels:
      version: 4.2.0

    volumeMounts:
      - name: jmx-exporter
        mountPath: /jmx
---
# Monitor to scrape the metrics from the Spark driver and executor pods
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-pod-monitor
  namespace: spark-jobs
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      name: spark-observability-demo

  podMetricsEndpoints:
    - port: jmx-exporter
